github:
  description: "Working Groups Documents for the Apache Community Development"
  homepage: https://community.apache.org/
  labels:
    - apache
    - community
    - comdev

notifications:
  commits:      commits@community.apache.org
  issues:       notification@community.apache.org
  pullrequests: notification@community.apache.org
  jira_options: link label
